services:
  vue-app:
    build:
      context: ./budget_list_depot
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expone la aplicación Vue en el puerto 8080
    networks:
      - app-network

  node-app:
    build:
      context: ./PlaywrightDepot
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expone la aplicación Node.js en el puerto 3000
    networks:
      - app-network
    environment:
      DISPLAY: ":99" # Configura la variable de entorno para Xvfb

networks:
  app-network:
    driver: bridge

